-- Licensed Materials - Property of IBM
--
-- BI and PM: CM
--
-- (C) Copyright IBM Corp. 2010
--
-- US Government Users Restricted Rights - Use, duplication or disclosure
-- restricted by GSA ADP Schedule Contract with IBM Corp.

-- Copyright (C) 2008 Cognos ULC, an IBM Company. All rights reserved.
-- Cognos (R) is a trademark of Cognos ULC, (formerly Cognos Incorporated).

-- Use this template to create the IBM Cognos content database. Replace these variables:  
-- cm : Database name
-- db2inst1 : User ID, this account is used by the product to connect to the content store
-- This script must be run as a user that has sufficient privileges to access and create the database. 
-- The database user account meeds to exist for the product to function.

CREATE DATABASE cm AUTOMATIC STORAGE YES ALIAS cm USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 8192;
CHANGE DATABASE cm COMMENT WITH 'IBM Cognos Content Store';
CONNECT TO cm;
UPDATE DATABASE CONFIGURATION USING APPLHEAPSZ 1024 DEFERRED;
UPDATE DATABASE CONFIGURATION USING LOCKTIMEOUT 240 DEFERRED; 
CONNECT RESET;

CONNECT TO cm;
CREATE BUFFERPOOL cm_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
CREATE BUFFERPOOL cm_32KBP IMMEDIATE SIZE 1000 PAGESIZE 32K;
CONNECT RESET;

CONNECT TO cm;
CREATE SYSTEM TEMPORARY TABLESPACE TSN_SYS_cm IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 32K BUFFERPOOL cm_32KBP;
CREATE USER TEMPORARY TABLESPACE TSN_USR_cm IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL IBMDEFAULTBP;
CREATE REGULAR TABLESPACE TSN_REG_cm IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL cm_08KBP; 
DROP TABLESPACE USERSPACE1;
CONNECT RESET;

CONNECT TO cm;
CREATE SCHEMA db2COGNOS AUTHORIZATION db2inst1;
COMMENT ON SCHEMA db2COGNOS IS 'IBM Cognos Content Store';
GRANT CREATETAB,BINDADD,CONNECT,IMPLICIT_SCHEMA ON DATABASE  TO USER db2inst1;
GRANT CREATEIN,DROPIN,ALTERIN ON SCHEMA DB2COGNOS TO USER db2inst1;
GRANT USE OF TABLESPACE TSN_USR_cm TO USER db2inst1;
GRANT USE OF TABLESPACE TSN_REG_cm TO USER db2inst1;
CONNECT RESET;
