FROM consol/centos-xfce-vnc

MAINTAINER Philippe Gregoire

# VNC and HTML-VNC ports
EXPOSE 5901 6901

# Switch to root user
USER 0

#######################################################################################################
# Cognos setup
# Based on RHEL Dockerfile from dnastaci@us.ibm.com

# Cognos settings
ENV COGNOS_BASE_DIR /opt/ibm/cognos
ENV COGNOS_DIR      ${COGNOS_BASE_DIR}/analytics

ENV COGNOS_USER     cognosusr
ENV COGNOS_UID		1001
ENV COGNOS_GID		1000

ENV COGNOS_MEDIA_DIR	/installer/cognos

ARG COGNOS_PROPERTIES=cognosca_reponse.properties
ARG COGNOS_HOST=cognos11srv

# IBM Cognos Analytics Installer 2.0 Linux x86 Multilingual (CNV5CML)
ARG COGNOS_INSTALLER=ca_installer_linuxi38664_2.0.bin

# IBM Cognos Analytics Server 11.1.1 Linux x86 Multilingual (CNV5BML) or (CNZ14ML)
ARG COGNOS_SERVER_IMAGE=ca_server_linuxi38664_11.1.1.zip

# IBM Cognos Analytics Samples 11.0 Linux x86-64 Multilingual (CN8AFML)
ARG COGNOS_SAMPLES=ca_smpl_lnxi38664_11.0.0.15121603.bin

# Cognos Prepreq (See https://www.ibm.com/support/knowledgecenter/en/SS5R93_5.3.0/com.ibm.spectrum.sc.doc/ins_cognos_analytics_Linux_single.html)
#glibc-2.12-1.166.el6 or later (both i686 and x86_64 packages)
#libstdc++-4.4.7-16.el6 or later (both i686 and x86_64 packages)
#nspr-4.9.2-1.el6 or later (both i686 and x86_64 packages)
#nss-3.14.0.0-12.el6 or later (both i686 and x86_64 packages)
#openmotif-2.3.3-5.el6 or later (both i686 and x86_64 packages)
RUN yum install -y \
		glibc.x86_64 glibc.i686 \
		libstdc++.x86_64 libstdc++.i686 \
		nspr.x86_64 nspr.i686 \
		nss.x86_64 nss.i686 \
		openmotif.x86_64 openmotif.i686 \
	&& yum clean all && rm -rf /tmp/*

#
# Install other dependencies
#
# "which is required for Cognos installation
# "glibc.i686" is required for Cognos installation
# "tigervnc-server xorg-x11-twm xorg-x11-server-utils xterm" are required for cogconfig.sh in XTerminal mode
# "nc" is required by cognos-setup.sh
#
RUN echo "Installing X11" && \
	yum install -y \
	which \
	unzip \
	sudo \
	nano \
	rsync \
#	gedit \
	libstdc++ libstdc++.i686 \
	libX11 libX11.i686 \
	tigervnc-server xorg-x11-twm xorg-x11-server-utils xterm \
	&& yum clean all && rm -rf /tmp/*
	
# For the record, re: https://www.ibm.com/support/knowledgecenter/SSEP7J_11.0.0/com.ibm.swg.ba.cognos.inst_cr_winux.doc/c_inst_ulimitsettingsonunixandlinuxoperatingsystems.html
RUN \
	ulimit -f -t -u -m -n -s -v && \
	echo "Current hostname: `hostname`"
	
# Copy Cognos installer files into the container's filesystem
COPY /media/$COGNOS_INSTALLER ${COGNOS_MEDIA_DIR}/
COPY /media/$COGNOS_SERVER_IMAGE ${COGNOS_MEDIA_DIR}/
COPY /media/$COGNOS_SAMPLES ${COGNOS_MEDIA_DIR}/

# Copy properties
COPY ${COGNOS_PROPERTIES} ${COGNOS_MEDIA_DIR}
	
# Setup Cognos user as user 1001 and run installer
RUN \
	groupadd -f -g ${COGNOS_GID} ${COGNOS_USER} && \
	useradd -u ${COGNOS_UID} -g ${COGNOS_GID} ${COGNOS_USER} -m && \
	mkdir -p "${COGNOS_DIR}" && \
	chown -R ${COGNOS_USER}:${COGNOS_USER} "${COGNOS_BASE_DIR}" && \
	chmod -R uo+x "${COGNOS_MEDIA_DIR}/${COGNOS_INSTALLER}"

# Run installer
RUN \
	echo "Running cognos silent installer" && \
	echo REPO=${COGNOS_MEDIA_DIR}/${COGNOS_SERVER_IMAGE} >>${COGNOS_MEDIA_DIR}/${COGNOS_PROPERTIES} && \
	cat ${COGNOS_MEDIA_DIR}/${COGNOS_PROPERTIES} && \
	echo "BUILD_HOST=`hostname`"> ${COGNOS_BASE_DIR}/build_host.txt && \
	su - ${COGNOS_USER} -c "\"${COGNOS_MEDIA_DIR}/${COGNOS_INSTALLER}\" -f \"${COGNOS_MEDIA_DIR}/${COGNOS_PROPERTIES}\" -i silent" && \
	cp ${COGNOS_DIR}/configuration/cogstartup.xml ${COGNOS_DIR}/configuration/cogstartup.xml_`hostname` && \
	sed -i "s/`hostname`/${COGNOS_HOST}/g" ${COGNOS_DIR}/configuration/cogstartup.xml && \
	cp ${COGNOS_DIR}/configuration/cogstartup.xml ${COGNOS_DIR}/configuration/cogstartup.xml_${COGNOS_HOST}

# Copy db2jcc JDBC drivers (obtained from db2-developer-c container)
COPY /media/db2jcc.jar ${COGNOS_DIR}/drivers/
COPY /media/db2jcc4.jar ${COGNOS_DIR}/drivers/
COPY /media/db2jcc_license_cu.jar ${COGNOS_DIR}/drivers/

RUN chmod +x ${COGNOS_DIR}/drivers/db2jcc*.jar

# Set JAVA_HOME
RUN \
	echo export JAVA_HOME=${COGNOS_DIR}/jre >> /home/${COGNOS_USER}/.bashrc && \
	echo export JAVA_HOME=${COGNOS_DIR}/jre >> /home/${VNC_USER_ID}/.bashrc && \
	echo export JAVA_HOME=${COGNOS_DIR}/jre >> /root/.bashrc
		
# Cognos UI port
EXPOSE 9300

# Copy desktop shortcuts
COPY Cognos_Config.desktop /headless/Desktop

# Switch back to regular user
USER 1000

# Keep the wait command so that the image stays up
CMD ["-d --wait"]